import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { twMerge } from 'tailwind-merge'
import './globals.css'

const inter = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={twMerge(inter.className, 'flex flex-col')}>
        {children}
      </body>
    </html>
  )
}
